version: '3.5'

services:
  # api:
  #   container_name: api
  #   build:
  #     context: ./api
  #   environment:
  #     PORT: '8080'
  #     PG_URI: 'user=docker password=docker host=postgres port=5432 dbname=docker sslmode=disable'
  #     JWT_KEY: '123'
  #   ports:
  #     - '8080:8080'
  #   networks:
  #     - default
  #   restart: unless-stopped

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: docker
      PGDATA: /data/postgres
    networks:
      - default
    volumes:
      - postgres:/data/postgres
      - ./setup-database.sql:/docker-entrypoint-initdb.d/0_init.sql
    ports:
      - '5432:5432'
    restart: unless-stopped

  localstack:
    container_name: localstack
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-} 
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
  postgres:
