version: '3.5'

services:
  # comentado apenas para subir o banco de dados local sem subir a aplicação
  # api-charge-friends:
  #   container_name: api-charge-friends
  #   build:
  #     context: .
  #   environment:
  #     PORT: '8080'
  #     PG_URI: 'user=docker password=docker host=postgres port=5432 dbname=docker sslmode=disable'
  #     JWT_KEY: '123'
  #   ports:
  #     - '8080:8080'
  #   networks:
  #     - charge-friends
  #   restart: unless-stopped

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: docker
      PGDATA: /data/postgres
    networks:
      - charge-friends
    volumes:
      - postgres:/data/postgres
      - ./setup-database.sql:/docker-entrypoint-initdb.d/0_init.sql
    ports:
      - '5432:5432'
    restart: unless-stopped

networks:
  charge-friends:
    driver: bridge

volumes:
  postgres:
